spring:
  rabbitmq:
    host: 192.168.99.100
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:my_database
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
